### ISSUE TITLE
Dataset creation error

### ISSUE THREAD

**Issue by tomh5905** [adrianalbert/urban-environments#1]
I am a student trying to recreate your dataset for a Delft University of Technology Deep Learning course project. During the walk-through of your dataset creation notebook, I keep running into the same problem in the line `mycity_crop = mycity.crop_centered_window(city_center, (25,25))`. In the `filter_gdf_by_polygon` function that is called, `spatial_index = gdf.sindex` returns `None`, which of course breaks the rest of the pipeline. If I only print `gdf` I do see a filled dataframe for the example city. Are you familiar with this issue?

**Comment by tomh5905** [comment]
Sorry, I found the fix myself! I did not have the libspatialindex package installed correctly (http://libspatialindex.github.io).

**Comment by maifeeulasad** [comment]
@tomharting can you share your approach with a little more details. I'm also facing the same error: https://github.com/adrianalbert/pysatml/issues/5

I tried these solutions : 
```
sudo apt install libspatialindex-dev
```
And : 
```
https://github.com/libspatialindex/libspatialindex.git
cd libspatialindex
cmake -DCMAKE_INSTALL_PREFIX=/home/maifee/usr .
make
make install
```
Still getting the same error. Can you share your configurations. Please.
